<a href="https://colab.research.google.com/github/Emmanuel10701/Numpy/blob/main/Group_3_Python_Discussion_Matrices_And_NumPy_Practice_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Question 4. Creating and multiplying matrices.**

In [ ]:
import numpy as np

A = np.array([[3, 2, 2],
              [2, 3, -2]])
B = np.array([[1, 0],
              [0, 1],
              [1, 1]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)


# A * B
A_dot_B = A @ B
print("\nA * B (A @ B):\n", A_dot_B)

# A.T * A
A_T_A = A.T @ A
print("\nA.T * A:\n", A_T_A)

# A * A.T
A_A_T = A @ A.T
print("\nA * A.T:\n", A_A_T)

Matrix A:
 [[ 3  2  2]
 [ 2  3 -2]]

Matrix B:
 [[1 0]
 [0 1]
 [1 1]]

A * B (A @ B):
 [[5 4]
 [0 1]]

A.T * A:
 [[13 12  2]
 [12 13 -2]
 [ 2 -2  8]]

A * A.T:
 [[17  8]
 [ 8 17]]


**Question 5. Determinants and Inverses.**




In [ ]:
import numpy as np

C = np.array([[1, 2],
              [3, 4]])
print("Matrix C:\n", C)

# (i) The determinant of C
det_C = np.linalg.det(C)
print(f"\nDeterminant of C: {det_C}")

# (ii) The inverse of C (if it exists)
try:
    inv_C = np.linalg.inv(C)
    print("\nInverse of C:\n", inv_C)
except np.linalg.LinAlgError as e:
    print(f"\nInverse of C does not exist: {e}")

Matrix C:
 [[1 2]
 [3 4]]

Determinant of C: -2.0000000000000004

Inverse of C:
 [[-2.   1. ]
 [ 1.5 -0.5]]


**Question 6. Eigenvalues and Eigenvectors.**



In [ ]:
import numpy as np

M = np.array([[4, 1],
              [1, 3]])
print("Symmetric Matrix M:\n", M)

# (i) The eigenvalues of M
# (ii) The corresponding eigenvectors
eigenvalues_M, eigenvectors_M = np.linalg.eig(M)

print("\nEigenvalues of M:\n", eigenvalues_M)
print("\nCorresponding Eigenvectors of M (columns of the matrix are eigenvectors):\n", eigenvectors_M)

Symmetric Matrix M:
 [[4 1]
 [1 3]]

Eigenvalues of M:
 [4.61803399 2.38196601]

Corresponding Eigenvectors of M (columns of the matrix are eigenvectors):
 [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]


**Question 7. SVD.**

In [ ]:
import numpy as np

A_svd = np.array([[3, 2, 2],
                  [2, 3, -2]])
print("Matrix A for SVD:\n", A_svd)

# Compute the SVD: A = U * Sigma * V.T
U, s, Vt = np.linalg.svd(A_svd)



print("\nIdentified components:")
print("\n(i) Left singular vectors (columns of U):\n", U)
print("\n(ii) Right singular vectors (rows of V.T):\n", Vt)
print("\n(iii) Singular values (s):\n", s)

Matrix A for SVD:
 [[ 3  2  2]
 [ 2  3 -2]]

Identified components:

(i) Left singular vectors (columns of U):
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

(ii) Right singular vectors (rows of V.T):
 [[-7.07106781e-01 -7.07106781e-01 -6.47932334e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]

(iii) Singular values (s):
 [5. 3.]
